#!/usr/bin/env groovy
pipeline {
    agent any

    agent {
        docker { image 'node:14.15.0'}
    }
    stages {
        stage('Build') {
            steps {
                sh "node --version"
                sh "npm install"
            }
        }
    }
}
