#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker { image 'node'}
            }
            steps {
                sh "npm start"
            }
        }
    }
}
